---
- name: Check HA state input value
  ansible.builtin.fail:
    msg:
      "role_nutanix_pe_ahv_vm_ha_desired_state: '{{ role_nutanix_pe_ahv_vm_ha_desired_state }}' is not allowed. \
      Please set role_nutanix_pe_ahv_vm_ha_desired_state to one of these values; {{ role_nutanix_pe_ahv_vm_ha_allowed_states }}"
  when:
    - role_nutanix_pe_ahv_vm_ha_desired_state not in role_nutanix_pe_ahv_vm_ha_allowed_states
