---
# tasks file for role_nutanix_pe_ahv_vm_ha
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_pe_ahv_vm_ha_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_pe_ahv_vm_ha_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_pe_ahv_vm_ha_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_pe_ahv_vm_ha_host_port | default(omit) }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_pe_ahv_vm_ha_host_validate_certs | default(omit) }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_pe_ahv_vm_ha_debug | default(omit) }}"

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "'role_nutanix_pe_ahv_vm_ha_host' needs to be set to the VIP of a Nutanix cluster. Please check the variable and try again."
  when:
    - role_nutanix_prism_api_endpoint_type != 'pe'

- name: Check input variables
  include_tasks: check_inputs.yml

- name: Gather variables for HA configuration update
  include_tasks: set_variables.yml

- name: Perform Prism HA configuration update if necessary
  include_tasks: update_ha.yml
  when:
    - role_nutanix_pe_ahv_vm_ha_update is defined
    - role_nutanix_pe_ahv_vm_ha_cluster_is_ahv is defined
