---
- name: Get current cluster configuration
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster"
    method: GET
    validate_certs: "{{ role_nutanix_pe_ahv_vm_ha_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_pe_ahv_vm_ha_current_config

- name: Debug role_nutanix_pe_ahv_vm_ha_current_config.json
  debug:
    var: role_nutanix_pe_ahv_vm_ha_current_config.json
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Set fact role_nutanix_pe_ahv_vm_ha_cluster_is_ahv
  set_fact:
    role_nutanix_pe_ahv_vm_ha_cluster_is_ahv:
  when: '"kKvm" in role_nutanix_pe_ahv_vm_ha_current_config.json.hypervisor_types'

- name: Debug role_nutanix_pe_ahv_vm_ha_cluster_is_ahv
  debug:
    var: role_nutanix_pe_ahv_vm_ha_cluster_is_ahv
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Set fact role_nutanix_pe_ahv_vm_ha_cluster_rf_level
  set_fact:
    role_nutanix_pe_ahv_vm_ha_cluster_rf_level: "{{ role_nutanix_pe_ahv_vm_ha_current_config.json.cluster_redundancy_state.current_redundancy_factor }}"

- name: Debug role_nutanix_pe_ahv_vm_ha_cluster_rf_level
  debug:
    var: role_nutanix_pe_ahv_vm_ha_cluster_rf_level
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Get current HA config
  uri:
    url: "https://{{ role_nutanix_pe_ahv_vm_ha_host }}:{{ role_nutanix_pe_ahv_vm_ha_port }}/PrismGateway/services/rest/v2.0/ha"
    method: GET
    validate_certs: "{{ role_nutanix_pe_ahv_vm_ha_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: nutanix_prism_ha_current_config

- name: Debug nutanix_prism_ha_current_config.json
  debug:
    var: nutanix_prism_ha_current_config.json
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Set default role_nutanix_pe_ahv_vm_ha_failover_enabled for "{{ role_nutanix_pe_ahv_vm_ha_desired_state }}"
  set_fact:
    role_nutanix_pe_ahv_vm_ha_failover_enabled: >-
      {{ role_nutanix_pe_ahv_vm_ha_state_defaults
      | json_query(query) | first
      | json_query('failover_enabled') }}
    role_nutanix_pe_ahv_vm_ha_reservation_type: >-
      {{ role_nutanix_pe_ahv_vm_ha_state_defaults
      | json_query(query) | first
      | json_query('reservation_type') }}
    role_nutanix_pe_ahv_vm_ha_reservation_type_comparison: >-
      {{ role_nutanix_pe_ahv_vm_ha_state_defaults
      | json_query(query) | first
      | json_query('reservation_type_comparison') }}
  vars:
    query: "[?ha_state==`{{ role_nutanix_pe_ahv_vm_ha_desired_state }}`]"
  when:
    - role_nutanix_pe_ahv_vm_ha_failover_enabled is undefined

- name: Debug role_nutanix_pe_ahv_vm_ha_failover_enabled
  debug:
    var: role_nutanix_pe_ahv_vm_ha_failover_enabled
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_failover_enabled
  debug:
    var: role_nutanix_pe_ahv_vm_ha_failover_enabled
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_reservation_type
  debug:
    var: role_nutanix_pe_ahv_vm_ha_reservation_type
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug nutanix_prism_ha_res_type_comp
  debug:
    var: nutanix_prism_ha_res_type_comp
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Set default role_nutanix_pe_ahv_vm_ha_host_failures for "{{ role_nutanix_pe_ahv_vm_ha_desired_state }}"
  set_fact:
    role_nutanix_pe_ahv_vm_ha_host_failures: "{{ role_nutanix_pe_ahv_vm_ha_cluster_rf_level | int - 1 }}"
  when:
    - role_nutanix_pe_ahv_vm_ha_host_failures is undefined
    - role_nutanix_pe_ahv_vm_ha_desired_state != "BestEffort"

- name: Debug role_nutanix_pe_ahv_vm_ha_host_failures
  debug:
    var: role_nutanix_pe_ahv_vm_ha_host_failures
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Set default role_nutanix_pe_ahv_vm_ha_host_failures for "BestEffort"
  set_fact:
    role_nutanix_pe_ahv_vm_ha_host_failures: "0"
  when:
    - role_nutanix_pe_ahv_vm_ha_host_failures is undefined
    - role_nutanix_pe_ahv_vm_ha_desired_state == "BestEffort"

- name: Compare current HA config to desired state
  set_fact:
    role_nutanix_pe_ahv_vm_ha_update:
  when:
    ( nutanix_prism_ha_current_config.json.ha_state != role_nutanix_pe_ahv_vm_ha_desired_state or
    nutanix_prism_ha_current_config.json.failover_enabled != role_nutanix_pe_ahv_vm_ha_failover_enabled or
    nutanix_prism_ha_current_config.json.reservation_type != role_nutanix_pe_ahv_vm_ha_reservation_type_comparison or
    nutanix_prism_ha_current_config.json.num_host_failures_to_tolerate | int != role_nutanix_pe_ahv_vm_ha_host_failures | int )

- name: Debug role_nutanix_pe_ahv_vm_ha_update
  debug:
    var: role_nutanix_pe_ahv_vm_ha_update
  when:
    - role_nutanix_pe_ahv_vm_ha_debug
