---
- name: Debug role_nutanix_pe_ahv_vm_ha_failover_enabled
  debug:
    var: role_nutanix_pe_ahv_vm_ha_failover_enabled
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_desired_state
  debug:
    var: role_nutanix_pe_ahv_vm_ha_desired_state
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_reservation_type
  debug:
    var: role_nutanix_pe_ahv_vm_ha_reservation_type
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_host_failures
  debug:
    var: role_nutanix_pe_ahv_vm_ha_host_failures
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Debug role_nutanix_pe_ahv_vm_ha_update_task
  debug:
    msg: "{{ lookup('template', 'ha.j2') | from_yaml | to_nice_json }}"
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Update AHV VM HA configuration
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/ha"
    method: PUT
    validate_certs: "{{ role_nutanix_pe_ahv_vm_ha_host_validate_certs }}"
    body: "{{ lookup('template', 'ha.j2') | from_yaml | to_json }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_pe_ahv_vm_ha_update_task
  changed_when: true

- name: Debug role_nutanix_pe_ahv_vm_ha_update_task
  debug:
    var: role_nutanix_pe_ahv_vm_ha_update_task
  when:
    - role_nutanix_pe_ahv_vm_ha_debug

- name: Wait for AHV VM HA configuration task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pe_ahv_vm_ha_host }}"
    role_nutanix_prism_monitor_task_host_username: "{{ role_nutanix_pe_ahv_vm_ha_host_username }}"
    role_nutanix_prism_monitor_task_host_password: "{{ role_nutanix_pe_ahv_vm_ha_host_password }}"
    role_nutanix_prism_monitor_task_host_port: "{{ role_nutanix_pe_ahv_vm_ha_host_port | default(omit) }}"
    role_nutanix_prism_monitor_task_host_validate_certs: "{{ role_nutanix_pe_ahv_vm_ha_host_validate_certs | default(omit) }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pe_ahv_vm_ha_debug | default(omit) }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_pe_ahv_vm_ha_update_task.json.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: 60
    role_nutanix_prism_monitor_task_retry_delay: 10

- name: Set role_nutanix_prism_monitor_task_result
  set_fact:
    prism_ha_update_task_status: "{{ role_nutanix_prism_monitor_task_result }}"

- name: Debug prism_ha_update_task_status
  debug:
    var: prism_ha_update_task_status
  when:
    - role_nutanix_pe_ahv_vm_ha_debug
